#!/bin/bash
set -euo pipefail

images="kubewarden-images.tar.gz"
list="kubewarden-images.txt"

usage () {
    echo "USAGE: $0 [--images kubewarden-images.tar.gz] --registry my.registry.com:5000"
    echo "  [-l|--image-list path] text file with list of images; one image per line."
    echo "  [-i|--images path] tar.gz generated by docker save."
    echo "  [-r|--registry registry:port] target private registry in the registry:port format."
    echo "  [-h|--help] Usage message"
}

while [[ $# -gt 0 ]]; do
    key="$1"
    shift
    case $key in
        -r|--registry)
        registry="$1"
        shift # past value
        ;;
        -l|--image-list)
        list="$1"
        shift # past value
        ;;
        -i|--images)
        images="$1"
        shift # past value
        ;;
        -h|--help)
        help="true"
        ;;
        *)
        usage
        exit 1
        ;;
    esac
done
if [[ -z "${registry}" ]]; then
    usage
    exit 1
fi
if [[ -v help ]]; then
    usage
    exit 0
fi

docker load --input "${images}"

linux_images=()
while IFS= read -r i; do
    [ -z "${i}" ] && continue
    linux_images+=("${i}");
done < "${list}"

for image in "${linux_images[@]}"; do
    [ -z "${image}" ] && continue

    oldRegistry=$(echo "$image" | cut -f1 -d"/")
    # replace existing registry with the one provided as parameter
    imageNewRegistry="${image/$oldRegistry/$registry}"
    docker tag "${image}" "${imageNewRegistry}"
    docker push "${imageNewRegistry}"
done
